

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: hacker-company
  labels:
    app: redis-deployment
    chart: redis

spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-deployment
          image: redis
          port: 6379
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: dev
            - name: SERVICE_NAME
              value: redis
            - name: AWS_REGION
              value: us-east-1


